<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>termsAndConditionsCheckbox</name>
   <tag></tag>
   <elementGuidId>6140a533-c4a7-40b6-9efd-ee00434070c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//label)[1]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//label)[1]/i</value>
   </webElementProperties>
</WebElementEntity>
